TEMPLATE	= lib
CONFIG		= staticlib qt warn_on release
HEADERS		= ../../../include/qxt.h
SOURCES		= qxt.cpp
MOC_DIR		= .
TARGET		= qxt
DESTINCDIR	= ../../../include
DESTDIR		= ../../../lib
VERSION		= 0.3
