/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 100
#define YY_END_OF_BUFFER 101
static yyconst short int yy_accept[371] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  101,  100,   91,   99,
      100,   91,   88,   96,   91,   62,   96,   60,   60,   60,
       91,   88,   97,   91,   67,   97,   97,   97,   84,   97,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   91,   88,   92,   91,
       63,   92,   61,   61,   61,   61,    7,    8,   91,   88,
       94,   91,   65,   16,   17,   20,   94,   21,   18,   19,
       91,   88,   93,   91,   64,   93,    5,    6,   91,   88,
       95,   91,   66,   24,   25,   95,   22,   23,   26,   27,

       91,   88,   98,   91,   98,   91,   88,   91,   90,   89,
       91,   88,   88,   88,   62,   60,   60,   60,   67,    0,
       77,    0,    0,   86,   85,   84,   56,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   63,   61,   61,   61,   61,   61,
       61,   65,   64,   66,   89,   88,   60,   60,   68,    0,
        0,   68,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   57,   85,   59,   51,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   40,   59,   59,

       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   61,   61,   61,   61,
       61,   61,   88,   60,   60,   83,   79,   78,   80,    0,
       81,   76,   69,   70,   71,   72,   73,   74,   75,    0,
       59,   30,   38,   59,   59,   59,   47,   59,   59,   59,
       59,   41,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   46,   59,   61,
       61,   61,   61,   61,   61,   88,    1,   60,   81,   82,
       59,   48,   36,   59,   59,   44,   59,   59,   59,   59,
       59,   59,   59,   39,   59,   59,    4,   59,   59,   59,

       59,   50,   59,   59,   59,   61,   61,   61,   61,   61,
       13,   88,   60,   59,   45,   33,   28,   34,   59,   59,
       59,   54,   59,   59,   42,   32,   49,   59,   59,   59,
       59,   59,   61,   61,   61,    9,   61,   88,   60,   59,
       59,   52,   59,   59,    3,   59,   29,   59,   35,   59,
       61,   11,   61,   12,   88,   88,    2,   15,   55,   59,
       31,   58,   43,   37,   14,   61,   87,   53,   10,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    4,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    5,    6,    1,    1,    1,    7,    8,
        9,   10,    1,   11,    1,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   16,   16,   17,   18,   19,
        1,   20,    1,    1,   21,   22,   23,   21,   24,   21,
       25,   25,   25,   26,   25,   25,   25,   25,   27,   25,
       28,   25,   25,   29,   25,   25,   25,   25,   25,   25,
       30,   31,   32,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   25,   25,   43,   44,   45,
       46,   47,   25,   48,   49,   50,   51,   52,   25,   53,
       54,   25,   55,    1,   56,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[57] =
    {   0,
        1,    1,    1,    2,    3,    1,    4,    1,    1,    1,
        1,    1,    1,    5,    5,    5,    1,    1,    1,    1,
        5,    5,    5,    5,    6,    6,    6,    6,    6,    1,
        1,    1,    6,    5,    5,    5,    5,    5,    5,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    1,    1
    } ;

static yyconst short int yy_base[391] =
    {   0,
        0,    3,   16,    5,   72,    9,  128,  182,  187,  218,
      199,  205,  260,  291,  212,  231,  685,  686,  184,  686,
      184,  236,  647,  686,  238,    0,  233,    0,  640,  644,
      250,  644,  686,  255,    0,  199,  260,  257,  269,  663,
        0,  646,  196,  245,  632,  206,  223,  632,  630,  628,
      250,  636,  264,  249,  628,  186,  306,  635,  686,  275,
        0,  303,    0,  638,  267,  277,  686,  686,  322,  633,
      686,  324,    0,  686,  686,  686,  319,  686,  686,  686,
      328,  632,  686,  333,    0,  327,  686,  686,  336,  631,
      686,  341,    0,  686,  686,  335,  686,  686,  686,  686,

      344,  630,  686,  349,  343,  352,  629,  357,  686,    0,
      359,    0,    0,  627,    0,    0,  630,  619,    0,  655,
      654,  361,  648,  355,  358,  365,  686,    0,  632,  614,
      607,  622,  621,  609,  602,  601,  601,  604,  607,  239,
      603,  609,  321,  611,  605,  598,  603,  596,  165,  597,
      593,  315,  591,  340,    0,    0,  611,  342,  602,  596,
      589,    0,    0,    0,    0,  595,  584,  585,  686,  624,
      623,  622,  371,  383,  621,  620,  619,  618,  617,  616,
      615,  614,  613,  686,  387,  597,    0,  572,  569,  567,
      566,  579,  569,  574,  577,  572,  567,    0,  568,  559,

      554,  555,  561,  561,  554,  556,  550,  549,  547,  550,
      558,  549,  552,  543,  555,  557,  568,  537,  538,  544,
      541,  535,  542,  534,  539,  686,  686,  686,  686,  401,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  574,
      554,    0,    0,  530,  528,  534,    0,  528,  525,  529,
      528,    0,  538,  537,  532,  527,  519,  517,  353,  517,
      523,  528,  520,  525,  516,  520,  508,    0,  508,  531,
      522,  517,  512,  519,  503,  506,    0,  516,  686,  686,
      525,    0,    0,  510,  502,    0,  509,  507,  494,  493,
      506,  505,  490,    0,  496,  501,    0,  501,  486,  501,

      496,    0,  488,  498,  489,  506,  479,  492,  491,  483,
        0,  487,  474,  500,    0,    0,    0,    0,  476,  483,
      466,    0,  470,  453,    0,    0,    0,  447,  452,  447,
      434,  425,  440,  417,  398,    0,  363,  379,  369,  376,
      356,    0,  361,  346,    0,  355,    0,  352,    0,  303,
      304,    0,  279,    0,  271,  318,    0,    0,    0,  212,
        0,    0,    0,    0,    0,  156,  686,    0,    0,  686,
      416,  422,  428,  434,  440,  446,  452,  454,  460,  466,
      468,  474,  476,  482,  488,  494,  500,  506,  509,  514
    } ;

static yyconst short int yy_def[391] =
    {   0,
      371,  371,  370,    3,  370,    5,  370,    7,  372,  372,
      373,  373,  374,  374,  375,  375,  370,  370,  370,  370,
      370,  370,  376,  370,  370,  377,  370,  378,  378,  378,
      370,  376,  370,  370,  379,  380,  370,  370,  370,  370,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  370,  376,  370,  370,
      382,  370,  383,  383,  383,  383,  370,  370,  370,  376,
      370,  370,  384,  370,  370,  370,  370,  370,  370,  370,
      370,  376,  370,  370,  385,  370,  370,  370,  370,  376,
      370,  370,  386,  370,  370,  370,  370,  370,  370,  370,

      370,  376,  370,  370,  370,  370,  376,  370,  370,  387,
      370,  376,  376,  376,  377,  378,  378,  378,  379,  370,
      370,  388,  370,  370,  370,  370,  370,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  382,  383,  383,  383,  383,  383,
      383,  384,  385,  386,  387,  376,  378,  378,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  389,  370,  370,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  383,  383,  383,  383,
      383,  383,  376,  378,  378,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  389,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  383,
      383,  383,  383,  383,  383,  376,  378,  378,  370,  370,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  383,  383,  383,  383,  383,
      383,  376,  378,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  383,  383,  383,  383,  383,  390,  378,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      383,  383,  383,  383,  390,  390,  378,  381,  381,  381,
      381,  381,  381,  381,  383,  383,  370,  381,  383,    0,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370
    } ;

static yyconst short int yy_nxt[743] =
    {   0,
      370,   19,   19,   20,   19,   22,   20,   31,   23,  370,
       32,   57,   21,  370,   58,   21,   24,   25,   25,   20,
       26,   24,   24,   24,   24,   24,   24,   24,   27,   24,
       24,   24,   24,   24,   24,   24,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   24,   24,   24,   28,   28,
       28,   29,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   30,   28,   28,   28,   28,
       24,   24,   33,   34,   34,   20,   35,   33,   36,   33,
       33,   33,   33,   37,   38,   39,   39,   39,   40,   33,
       33,   33,   41,   41,   41,   41,   41,   41,   41,   42,

       41,   33,   33,   33,   41,   43,   41,   44,   45,   46,
       47,   41,   41,   48,   49,   41,   41,   50,   51,   52,
       53,   54,   55,   56,   41,   41,   33,   33,   59,   60,
       60,   20,   61,   59,   59,   59,   59,   59,   59,   59,
       62,   59,   59,   59,   59,   59,   59,   59,   63,   63,
       63,   63,   63,   63,   63,   64,   63,   59,   59,   59,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   65,   63,   66,   63,   63,   63,
       63,   63,   67,   68,   69,  108,  108,   70,   72,   72,
       20,   73,  369,  109,   74,   75,  110,   76,  208,   77,

       84,   84,   20,   85,   78,  121,   84,   89,   20,   85,
       90,   86,  209,  104,  104,   20,   79,   86,   80,   72,
       81,   20,   73,   82,  105,   74,   75,  153,   76,  122,
       77,  154,  104,  106,   20,   78,  107,  108,  111,  108,
      108,  112,  109,  105,  130,  110,  131,   79,  368,   80,
      136,  108,  111,   87,   88,  112,  108,  108,  137,   87,
       88,   92,   92,   20,   93,  138,  109,   94,   95,  110,
      139,  123,   96,  124,  124,  124,  108,  108,   97,   98,
      125,  197,  126,  126,  126,  132,  150,  133,  198,   99,
      134,  100,   92,  101,   20,   93,  102,  143,   94,   95,

      144,  356,  151,   96,  146,  147,  148,  108,  111,   97,
       98,  112,  109,  149,  158,  110,  366,  159,  160,  161,
       99,  367,  100,  108,  111,  108,  108,  112,  109,  108,
      111,  110,  365,  112,  108,  108,  109,  108,  111,  110,
      364,  112,  108,  108,  109,  108,  111,  110,  356,  112,
      108,  108,  109,  108,  111,  110,  212,  112,  108,  108,
      108,  111,  201,  213,  112,  171,  202,  172,  124,  124,
      124,  185,  185,  185,  173,  174,  125,  229,  126,  126,
      126,  215,  216,  218,  230,  230,  295,  219,  363,  231,
      296,  175,  362,  361,  176,  177,  230,  230,  360,  178,

      185,  185,  185,  359,  358,  179,  357,  279,  180,  356,
      181,  354,  182,  183,  230,  230,   18,   18,   18,   18,
       18,   18,   71,   71,   71,   71,   71,   71,   83,   83,
       83,   83,   83,   83,   91,   91,   91,   91,   91,   91,
      103,  103,  103,  103,  103,  103,  113,  353,  113,  113,
      113,  113,  115,  115,  352,  115,  115,  115,  116,  116,
      119,  119,  351,  119,  119,  119,  120,  350,  120,  120,
      120,  120,  128,  128,  155,  155,  349,  155,  155,  155,
      156,  156,  162,  162,  348,  162,  162,  162,  163,  163,
      347,  163,  163,  163,  164,  164,  346,  164,  164,  164,

      165,  345,  165,  165,  165,  165,  170,  344,  170,  170,
      170,  170,  240,  240,  355,  343,  355,  355,  355,  355,
      342,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,

      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  226,
      239,  238,  237,  236,  235,  234,  233,  232,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  217,  214,  211,
      210,  207,  206,  205,  204,  203,  200,  199,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  184,
      169,  169,  168,  167,  166,  114,  114,  114,  114,  114,
      157,  114,  152,  145,  142,  141,  140,  135,  129,  127,
      114,  118,  117,  114,  370,   17,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,

      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370
    } ;

static yyconst short int yy_chk[743] =
    {   0,
        0,    1,    1,    1,    2,    2,    2,    4,    2,    0,
        4,    6,    1,    0,    6,    2,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    8,   19,   19,    8,    9,    9,
        9,    9,  366,   21,    9,    9,   21,    9,  149,    9,

       11,   11,   11,   11,    9,   36,   12,   12,   12,   12,
       12,   11,  149,   15,   15,   15,    9,   12,    9,   10,
       10,   10,   10,   10,   15,   10,   10,   56,   10,   36,
       10,   56,   16,   16,   16,   10,   16,   22,   22,   25,
       25,   22,   27,   16,   43,   27,   43,   10,  360,   10,
       46,   31,   31,   11,   11,   31,   34,   34,   46,   12,
       12,   13,   13,   13,   13,   47,   38,   13,   13,   38,
       47,   37,   13,   37,   37,   37,   60,   60,   13,   13,
       39,  140,   39,   39,   39,   44,   54,   44,  140,   13,
       44,   13,   14,   14,   14,   14,   14,   51,   14,   14,

       51,  355,   54,   14,   53,   53,   53,   57,   57,   14,
       14,   57,   62,   53,   65,   62,  353,   65,   66,   66,
       14,  356,   14,   69,   69,   72,   72,   69,   77,   81,
       81,   77,  351,   81,   84,   84,   86,   89,   89,   86,
      350,   89,   92,   92,   96,  101,  101,   96,  356,  101,
      104,  104,  105,  106,  106,  105,  152,  106,  108,  108,
      111,  111,  143,  152,  111,  122,  143,  122,  124,  124,
      124,  125,  125,  125,  122,  122,  126,  173,  126,  126,
      126,  154,  154,  158,  173,  173,  259,  158,  348,  174,
      259,  122,  346,  344,  122,  122,  174,  174,  343,  122,

      185,  185,  185,  341,  340,  122,  339,  230,  122,  338,
      122,  337,  122,  122,  230,  230,  371,  371,  371,  371,
      371,  371,  372,  372,  372,  372,  372,  372,  373,  373,
      373,  373,  373,  373,  374,  374,  374,  374,  374,  374,
      375,  375,  375,  375,  375,  375,  376,  335,  376,  376,
      376,  376,  377,  377,  334,  377,  377,  377,  378,  378,
      379,  379,  333,  379,  379,  379,  380,  332,  380,  380,
      380,  380,  381,  381,  382,  382,  331,  382,  382,  382,
      383,  383,  384,  384,  330,  384,  384,  384,  385,  385,
      329,  385,  385,  385,  386,  386,  328,  386,  386,  386,

      387,  324,  387,  387,  387,  387,  388,  323,  388,  388,
      388,  388,  389,  389,  390,  321,  390,  390,  390,  390,
      320,  319,  314,  313,  312,  310,  309,  308,  307,  306,
      305,  304,  303,  301,  300,  299,  298,  296,  295,  293,
      292,  291,  290,  289,  288,  287,  285,  284,  281,  278,
      276,  275,  274,  273,  272,  271,  270,  269,  267,  266,
      265,  264,  263,  262,  261,  260,  258,  257,  256,  255,
      254,  253,  251,  250,  249,  248,  246,  245,  244,  241,
      240,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,

      206,  205,  204,  203,  202,  201,  200,  199,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  186,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  172,  171,
      170,  168,  167,  166,  161,  160,  159,  157,  153,  151,
      150,  148,  147,  146,  145,  144,  142,  141,  139,  138,
      137,  136,  135,  134,  133,  132,  131,  130,  129,  123,
      121,  120,  118,  117,  114,  107,  102,   90,   82,   70,
       64,   58,   55,   52,   50,   49,   48,   45,   42,   40,
       32,   30,   29,   23,   17,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,

      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "moc.l"
#define INITIAL 0
/****************************************************************************
** $Id: moc.l,v 2.3.2.4 1998/09/24 15:36:49 eiriken Exp $
**
** Lexical analyzer for meta object compiler
**
** Created : 930417
**
** Copyright (C) 1993-1998 by Troll Tech AS.  All rights reserved.
**
** --------------------------------------------------------------------------
** This file contains the lexical analyzer for the meta object compiler (moc)
** of the Qt development framework.
*****************************************************************************/
#line 16 "moc.l"
#include "qstring.h"


#define input yyinput				// yyinput in C++

#define X if(lexDebug){fprintf(stderr,"LEX (%i) : %s\n",lineNo,yytext);};
#define Y if(lexDebug){fprintf(stderr,"LEX (%i) : %s updates level to %i\n"\
                               ,lineNo,yytext,templLevel);};
#define Z if(lexDebug){fprintf(stderr,"LEX (%i) : skipped the string %s\"\n"\
                               ,lineNo,yytext);};
#define BEGIN_INSIDE


#define  linput() (c = input()) == '\n' ? (lineNo++,c) : c

#include <string.h>
#include <stdlib.h>

/* char c,c1; */
int level      = 1;  /* Used to keep track of nested curly braces in IN_CLASS*/
int expLevel   = 1;  /* Used to keep track of nested parentheses in IN_EXPR */
int fctLevel   = 1;  /* Used to keep track of nested parentheses in IN_FCT */
int templLevel = 1;  /* Used to keep track of levels in IN_TEMPL_ARGS */


extern void addExpressionChar( char );
extern void addExpressionString( char * );
#define OUTSIDE 1
#define QT_DEF 2
#define IN_CLASS 3
#define IN_EXPR 4
#define IN_FCT 5
#define IN_TEMPL_ARGS 6
#define GIMME_SEMICOLON 7

#line 703 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 47 "moc.l"

#line 859 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yy_c_buf_p - yytext_ptr;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 371 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 686 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 48 "moc.l"
{ X;
				  BEGIN QT_DEF;
				  return CLASS; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 51 "moc.l"
{ X;
				  BEGIN QT_DEF;
				  return TEMPLATE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 54 "moc.l"
{ X;return SIGNALS; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 55 "moc.l"
{ X;return SLOTS; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 57 "moc.l"
{ fctLevel++;Y; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 58 "moc.l"
{ fctLevel--;Y;if (fctLevel==0){X;return '}';}}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 59 "moc.l"
{ level++;Y; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "moc.l"
{ level--;Y;if (level == 0) {X;return '}';} }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "moc.l"
{ X;return PUBLIC; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "moc.l"
{ X;return PROTECTED; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "moc.l"
{ X;return PRIVATE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 64 "moc.l"
{ X;return SIGNALS; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "moc.l"
{ X;return SLOTS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 66 "moc.l"
{ X;return Q_OBJECT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 67 "moc.l"
{ X;return Q_OBJECT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 68 "moc.l"
{ expLevel++;Y; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 69 "moc.l"
{ expLevel--;Y;if (expLevel == 0) 
					{ X; BEGIN QT_DEF; return ')';} }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "moc.l"
{ expLevel++;Y; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "moc.l"
{ expLevel--;Y;if (expLevel == 0) 
					{ X; BEGIN QT_DEF; return ']';} }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 74 "moc.l"
{ if (expLevel == 0) 
					{ X; BEGIN QT_DEF;return ',' ;} }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 76 "moc.l"
{ if (expLevel == 0)
					{ X; BEGIN QT_DEF;return ';' ;} }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 78 "moc.l"
{ templLevel++;Y; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 79 "moc.l"
{ templLevel--;Y;if (templLevel == 0) 
					{ X; BEGIN QT_DEF; return '>';} }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 81 "moc.l"
{ templLevel++;Y; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 82 "moc.l"
{ templLevel--;Y;if (templLevel == 0) 
					{ X; BEGIN QT_DEF; return ')';} }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 84 "moc.l"
{ templLevel++;Y; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 85 "moc.l"
{ templLevel--;Y;if (templLevel == 0) 
					{ X; BEGIN QT_DEF; return ']';} }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 87 "moc.l"
{ X;return FRIEND; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 88 "moc.l"
{ X;return TYPEDEF; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 89 "moc.l"
{ X;return AUTO; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 90 "moc.l"
{ X;return REGISTER; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 91 "moc.l"
{ X;return STATIC; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 92 "moc.l"
{ X;return EXTERN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 93 "moc.l"
{ X;return INLINE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 94 "moc.l"
{ X;return VIRTUAL; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 95 "moc.l"
{ X;return CONST; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 96 "moc.l"
{ X;return VOLATILE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 97 "moc.l"
{ X;return CHAR; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 98 "moc.l"
{ X;return SHORT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 99 "moc.l"
{ X;return INT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 100 "moc.l"
{ X;return LONG; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 101 "moc.l"
{ X;return SIGNED; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 102 "moc.l"
{ X;return UNSIGNED; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 103 "moc.l"
{ X;return FLOAT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 104 "moc.l"
{ X;return DOUBLE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 105 "moc.l"
{ X;return VOID; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 106 "moc.l"
{ X;return ENUM; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 107 "moc.l"
{ X;return CLASS; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 108 "moc.l"
{ X;return STRUCT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 109 "moc.l"
{ X;return UNION; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 110 "moc.l"
{ X;return ASM; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 111 "moc.l"
{ X;return PRIVATE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 112 "moc.l"
{ X;return PROTECTED; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 113 "moc.l"
{ X;return PUBLIC; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 114 "moc.l"
{ X;return OPERATOR; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 115 "moc.l"
{ X;return DBL_COLON; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 116 "moc.l"
{ X;return TRIPLE_DOT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 117 "moc.l"
{ X;return TEMPLATE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 119 "moc.l"
{
			  X;
			  yylval.string = qstrdup(yytext);
			  return IDENTIFIER;
			}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 125 "moc.l"
;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 126 "moc.l"
;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 128 "moc.l"
{			/* discard strings */
			  if (yytext[yyleng - 1] == '\\') {
			    yymore();
			  }
			  else {
			    Z;
			    input();		/* discard the '"' */
			  }
			}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 138 "moc.l"
{			/* discard strings */
			  if (yytext[yyleng - 1] == '\\') {
			    yymore();
			  }
			  else {
			    Z;
			    input();		/* discard the '"' */
			  }
			}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 148 "moc.l"
{			/* discard strings */
			  if (yytext[yyleng - 1] == '\\') {
			    yymore();
			  }
			  else {
			    Z;
			    input();		/* discard the '"' */
			  }
			}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 158 "moc.l"
{ 
			  if (yytext[yyleng - 1] == '\\') {
			    yymore();
			  }
			  else {
			    X;
			    addExpressionString(yytext);
			    input();		/* discard the '"' */
			    return STRING;
			  }
			}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 171 "moc.l"
{ if (yytext[yyleng - 1] == '\\') {
			      yymore();
			  }
			  else {
			      X;
			      addExpressionString(yytext);
			      input();		/* discard the '"' */
			      return STRING;
			 }
			}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 183 "moc.l"
{ if (yytext[yyleng - 1] == '\\') {
			      yymore();
			  }
			  else {
			      X;
			      yylval.string = qstrdup(yytext);
			      input();		/* discard the '"' */
			      return STRING;
			 }
			}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 195 "moc.l"
{ X;
			  yylval.char_val = yytext[1];
			  return CHAR_VAL;
			}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 200 "moc.l"
{ X;
			 yylval.char_val = '\a';
			 return CHAR_VAL;
		       }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 205 "moc.l"
{ X;
			 yylval.char_val = '\b';
			 return CHAR_VAL;
		       }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 210 "moc.l"
{ X;
			 yylval.char_val = '\f';
			 return CHAR_VAL;
		       }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 215 "moc.l"
{ X;
			 yylval.char_val = '\n';
			 return CHAR_VAL;
		       }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 220 "moc.l"
{ X;
			 yylval.char_val = '\r';
			 return CHAR_VAL;
		       }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 225 "moc.l"
{ X;
			 yylval.char_val = '\t';
			 return CHAR_VAL;
		       }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 230 "moc.l"
{ X;
			 yylval.char_val = '\v';
			 return CHAR_VAL;
		       }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 235 "moc.l"
{ X;
			 yylval.char_val = '\\';
			 return CHAR_VAL;
		       }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 240 "moc.l"
{ X;
			 yylval.char_val = '\?';
			 return CHAR_VAL;
		       }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 245 "moc.l"
{ X;
			 yylval.char_val = '\'';
			 return CHAR_VAL;
		       }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 250 "moc.l"
{ X;
			 yylval.char_val = '\"';	/* " */
			 return CHAR_VAL;
		       }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 255 "moc.l"
{ X;
			 yylval.char_val = '\0';
			 return CHAR_VAL;
		       }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 260 "moc.l"
{ X;
			 yylval.char_val =
			   (char)strtol( &yytext[1], 0, 8 );
			 return CHAR_VAL;
		       }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 266 "moc.l"
{ X;
			 yylval.char_val =
			   (char)strtol( &yytext[2], 0, 16 );
			 return CHAR_VAL;
		       }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 272 "moc.l"
{ X;
			 yylval.char_val = ' ';
			 return CHAR_VAL;
		       }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 277 "moc.l"
{ X;
			  yylval.int_val = atoi(yytext);
			  return INT_VAL;
			}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 282 "moc.l"
{ X;
			  yylval.double_val = atof(yytext);
			  return DOUBLE_VAL;
			}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 287 "moc.l"
{ X;
			  yylval.double_val = atof(yytext);
			  return DOUBLE_VAL;
			}
	YY_BREAK
case 87:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 293 "moc.l"
{ /* skip multi-line macro-definitions */
			  char c, c1;
			  input();   /* Discard the '\n'. */
			  do {
			      c1=' ';
			      while((c = linput()) != '\n' && c != 0) c1=c;
			      if (c == 0) break;
			  } while(c1=='\\');
			  unput(c);  /* put back the '\n' or the EOF */
			}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 304 "moc.l"
{ /* preprocessor commands are skipped */}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 305 "moc.l"
{ /* C++ comment */ }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 306 "moc.l"
{ /* C	 comment */
			  char c = ' ';
			  do {
			      if ( c!= '*' ) {
				  while((c = linput()) != '*' && c != 0)
				      ;
			      }
			      if (c == 0) break;
			  } while(((c = linput())) != '/' && c != 0);
			  if (c == 0)
			      unput(c);
			}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 319 "moc.l"
;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 320 "moc.l"
;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 321 "moc.l"
;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 322 "moc.l"
{ addExpressionChar( yytext[0] ); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 323 "moc.l"
{ addExpressionChar( yytext[0] ); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 324 "moc.l"
;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 325 "moc.l"
{
			  X;
			  return yytext[0];
			}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 329 "moc.l"
{
			  X;
			  return ';';
			}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 333 "moc.l"
{
			  lineNo++;
			}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 337 "moc.l"
ECHO;
	YY_BREAK
#line 1606 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(OUTSIDE):
case YY_STATE_EOF(QT_DEF):
case YY_STATE_EOF(IN_CLASS):
case YY_STATE_EOF(IN_EXPR):
case YY_STATE_EOF(IN_FCT):
case YY_STATE_EOF(IN_TEMPL_ARGS):
case YY_STATE_EOF(GIMME_SEMICOLON):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 371 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 371 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 370);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 337 "moc.l"




