TEMPLATE    =	lib
CONFIG      =   qt staticlib release opengl
HEADERS     =	../../../include/qgl.h
SOURCES     =	qgl.cpp
MOC_DIR     =   .
TARGET      =	qgl
DESTINCDIR  =   ../../../include
DESTDIR	    =   ../../../lib
VERSION     =	1.0
